apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsequeue-config
  namespace: pulsequeue-k3s
  labels:
    app.kubernetes.io/name: pulsequeue
    app.kubernetes.io/part-of: pulsequeue
data:
  PULSEQUEUE_HTTP_ADDR: ":8080"
  PULSEQUEUE_GRPC_ADDR: ":9090"
  PULSEQUEUE_API_URL: "http://pulsequeue-api:8080"
  PULSEQUEUE_NATS_URL: "nats://nats:4222"
  PULSEQUEUE_WORKER_QUEUE: "default"
  PULSEQUEUE_WORKER_CONCURRENCY: "1"
  PULSEQUEUE_WORKER_POLL_INTERVAL: "5s"
  PULSEQUEUE_WORKER_HEARTBEAT_INTERVAL: "10s"
  PULSEQUEUE_LEASE_DURATION: "60s"
  PULSEQUEUE_SCHEDULER_INTERVAL: "2s"
  PULSEQUEUE_SCHEDULER_BATCH_SIZE: "50"
  PULSEQUEUE_RETRY_INITIAL_DELAY: "2s"
  PULSEQUEUE_RETRY_MAX_DELAY: "30s"
  PULSEQUEUE_WORKER_METRICS_ADDR: ":2112"
  PULSEQUEUE_SCHEDULER_METRICS_ADDR: ":2112"
  PULSEQUEUE_OTEL_EXPORTER_OTLP_ENDPOINT: ""
