apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: pulsequeue-k3s
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: pulsequeue
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: pulsequeue-k3s
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: pulsequeue
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: pulsequeue
    spec:
      containers:
        - name: postgres
          image: postgres:18
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - shared_buffers=16MB
            - -c
            - max_connections=100
            - -c
            - work_mem=2MB
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: pulsequeue
            - name: POSTGRES_DB
              value: pulsequeue
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pulsequeue-secrets
                  key: postgres-password
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - pulsequeue
                - -d
                - pulsequeue
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 20
          livenessProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
